from typing import Dict, Any

class Delft3DConfigGenerator:
    """
    Generates Delft3D-FLOW Master Definition File (.mdf) and Grid Bathymetry (.dep) configuration input decks.
    """

    @staticmethod
    def generate_mdf_file(scenario: Dict[str, Any]) -> str:
        """
        Generates standard Delft3D-FLOW .mdf master definition file text deck.
        """
        title = scenario.get("title", "Tehri Dam-Break Flood Wave Run")
        sim_hours = scenario.get("duration_hr", 12.0)
        dt_min = scenario.get("time_step_sec", 60.0) / 60.0
        mannings_n = scenario.get("mannings_n", 0.035)

        mdf_content = f"""Ident  = #Delft3D-FLOW#
Record = 01.00
FileVer = #04.01#
Comment = # Generated by FloodHADR Delft3D Integration Architecture #
Ident  = #{title}#

[Files]
GrdFile = #tehri_valley.grd#
DepFile = #tehri_valley.dep#
BctFile = #tehri_breach.bct#
SrcFile = #tehri_spillway.src#

[Domain]
MNKmax = 120 80 1
Thick  = 100.0

[Time]
Tunit  = #M#
Tstart = 2026-08-01 00:00:00
Tstop  = 2026-08-01 {int(sim_hours):02d}:00:00
Dt     = {dt_min:.2f}

[PhysicalParameters]
Gravity = 9.81
Rho     = 1000.0
RoughnessFormula = #M#
RoughnessVal     = {mannings_n:.3f}
Viscosity        = 1.0

[Output]
MapFormat = #NEHIS#
HisFormat = #NEHIS#
MapInterval = 10.0
HisInterval = 1.0
"""
        return mdf_content

    @staticmethod
    def generate_dep_file(rows: int = 80, cols: int = 120) -> str:
        """Generates header template for Delft3D-FLOW bathymetry (.dep) elevation matrix."""
        dep_lines = [f"# Delft3D-FLOW Bathymetry Matrix ({cols} x {rows})"]
        for r in range(rows):
            row_vals = [f"{(300.0 + (r * 2.5) + (c * 0.5)):.1f}" for c in range(min(10, cols))]
            dep_lines.append(" ".join(row_vals) + " ...")
        return "\n".join(dep_lines)
